"""
NSE (National Stock Exchange of India) Ticker Universes
Includes Nifty 50, Nifty 100, and Nifty 500 equities with .NS suffix for yfinance.
"""

NIFTY_50 = [
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries Ltd", "sector": "Energy"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services Ltd", "sector": "Technology"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Ltd", "sector": "Financial Services"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Ltd", "sector": "Financial Services"},
    {"symbol": "INFY.NS", "name": "Infosys Ltd", "sector": "Technology"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Ltd", "sector": "Telecommunications"},
    {"symbol": "ITC.NS", "name": "ITC Ltd", "sector": "Consumer Goods"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "sector": "Financial Services"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro Ltd", "sector": "Construction"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Ltd", "sector": "Consumer Goods"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors Ltd", "sector": "Automobile"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical Ind Ltd", "sector": "Healthcare"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance Ltd", "sector": "Financial Services"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Ltd", "sector": "Financial Services"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki India Ltd", "sector": "Automobile"},
    {"symbol": "NTPC.NS", "name": "NTPC Ltd", "sector": "Utilities"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corp Ltd", "sector": "Energy"},
    {"symbol": "TITAN.NS", "name": "Titan Company Ltd", "sector": "Consumer Goods"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel Ltd", "sector": "Metals"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra Ltd", "sector": "Automobile"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corp of India Ltd", "sector": "Utilities"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises Ltd", "sector": "Metals & Mining"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Ltd", "sector": "Financial Services"},
    {"symbol": "COALINDIA.NS", "name": "Coal India Ltd", "sector": "Energy"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement Ltd", "sector": "Materials"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Ltd", "sector": "Consumer Goods"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum Corp Ltd", "sector": "Energy"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv Ltd", "sector": "Financial Services"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries Ltd", "sector": "Metals"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries Ltd", "sector": "Materials"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra Ltd", "sector": "Technology"},
    {"symbol": "CIPLA.NS", "name": "Cipla Ltd", "sector": "Healthcare"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd", "sector": "Financial Services"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India Ltd", "sector": "Consumer Goods"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel Ltd", "sector": "Metals"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp Ltd", "sector": "Automobile"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories Ltd", "sector": "Healthcare"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports & SEZ Ltd", "sector": "Infrastructure"},
    {"symbol": "WIPRO.NS", "name": "Wipro Ltd", "sector": "Technology"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Ltd", "sector": "Consumer Goods"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors Ltd", "sector": "Automobile"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Ltd", "sector": "Healthcare"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories Ltd", "sector": "Healthcare"},
    {"symbol": "LTIM.NS", "name": "LTIMindtree Ltd", "sector": "Technology"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance Co Ltd", "sector": "Financial Services"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Ltd", "sector": "Automobile"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance Co Ltd", "sector": "Financial Services"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance Ltd", "sector": "Financial Services"},
    {"symbol": "BEL.NS", "name": "Bharat Electronics Ltd", "sector": "Industrials"},
    {"symbol": "TRENT.NS", "name": "Trent Ltd", "sector": "Retail"}
]

# Additional Nifty Next 50 to complete Nifty 100
NIFTY_NEXT_50 = [
    {"symbol": "ABB.NS", "name": "ABB India Ltd", "sector": "Industrials"},
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy Ltd", "sector": "Utilities"},
    {"symbol": "ADANIPOWER.NS", "name": "Adani Power Ltd", "sector": "Utilities"},
    {"symbol": "ATGL.NS", "name": "Adani Total Gas Ltd", "sector": "Utilities"},
    {"symbol": "AMBUJACEM.NS", "name": "Ambuja Cements Ltd", "sector": "Materials"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda", "sector": "Financial Services"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints India Ltd", "sector": "Consumer Goods"},
    {"symbol": "BOSCHLTD.NS", "name": "Bosch Ltd", "sector": "Automobile"},
    {"symbol": "CANBK.NS", "name": "Canara Bank", "sector": "Financial Services"},
    {"symbol": "CHOLAFIN.NS", "name": "Cholamandalam Investment & Fin", "sector": "Financial Services"},
    {"symbol": "COLPAL.NS", "name": "Colgate-Palmolive India Ltd", "sector": "Consumer Goods"},
    {"symbol": "DLF.NS", "name": "DLF Ltd", "sector": "Real Estate"},
    {"symbol": "DABUR.NS", "name": "Dabur India Ltd", "sector": "Consumer Goods"},
    {"symbol": "GAIL.NS", "name": "GAIL India Ltd", "sector": "Utilities"},
    {"symbol": "GODREJCP.NS", "name": "Godrej Consumer Products Ltd", "sector": "Consumer Goods"},
    {"symbol": "HAVELLS.NS", "name": "Havells India Ltd", "sector": "Consumer Goods"},
    {"symbol": "HAL.NS", "name": "Hindustan Aeronautics Ltd", "sector": "Industrials"},
    {"symbol": "ICICIGI.NS", "name": "ICICI Lombard General Insurance", "sector": "Financial Services"},
    {"symbol": "ICICIPRULI.NS", "name": "ICICI Prudential Life Insurance", "sector": "Financial Services"},
    {"symbol": "IOC.NS", "name": "Indian Oil Corporation Ltd", "sector": "Energy"},
    {"symbol": "IRCTC.NS", "name": "Indian Railway Catering & Tourism", "sector": "Consumer Services"},
    {"symbol": "IRFC.NS", "name": "Indian Railway Finance Corp", "sector": "Financial Services"},
    {"symbol": "INDIGO.NS", "name": "InterGlobe Aviation Ltd", "sector": "Consumer Services"},
    {"symbol": "JINDALSTEL.NS", "name": "Jindal Steel & Power Ltd", "sector": "Metals"},
    {"symbol": "JIOFIN.NS", "name": "Jio Financial Services Ltd", "sector": "Financial Services"},
    {"symbol": "LICI.NS", "name": "Life Insurance Corp of India", "sector": "Financial Services"},
    {"symbol": "MARICO.NS", "name": "Marico Ltd", "sector": "Consumer Goods"},
    {"symbol": "MOTHERSON.NS", "name": "Samvardhana Motherson International", "sector": "Automobile"},
    {"symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance Ltd", "sector": "Financial Services"},
    {"symbol": "NAUKRI.NS", "name": "Info Edge India Ltd", "sector": "Technology"},
    {"symbol": "NHPC.NS", "name": "NHPC Ltd", "sector": "Utilities"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries Ltd", "sector": "Materials"},
    {"symbol": "PFC.NS", "name": "Power Finance Corporation Ltd", "sector": "Financial Services"},
    {"symbol": "PNB.NS", "name": "Punjab National Bank", "sector": "Financial Services"},
    {"symbol": "RECLTD.NS", "name": "REC Ltd", "sector": "Financial Services"},
    {"symbol": "SBICARD.NS", "name": "SBI Cards & Payment Services", "sector": "Financial Services"},
    {"symbol": "SRF.NS", "name": "SRF Ltd", "sector": "Materials"},
    {"symbol": "SIEMENS.NS", "name": "Siemens Ltd", "sector": "Industrials"},
    {"symbol": "TVSMOTOR.NS", "name": "TVS Motor Company Ltd", "sector": "Automobile"},
    {"symbol": "TATAPOWER.NS", "name": "Tata Power Company Ltd", "sector": "Utilities"},
    {"symbol": "TORNTPOWER.NS", "name": "Torrent Power Ltd", "sector": "Utilities"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals Ltd", "sector": "Healthcare"},
    {"symbol": "UNIONBANK.NS", "name": "Union Bank of India", "sector": "Financial Services"},
    {"symbol": "VBL.NS", "name": "Varun Beverages Ltd", "sector": "Consumer Goods"},
    {"symbol": "VEDL.NS", "name": "Vedanta Ltd", "sector": "Metals"},
    {"symbol": "ZOMATO.NS", "name": "Zomato Ltd", "sector": "Technology"},
    {"symbol": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences Ltd", "sector": "Healthcare"},
    {"symbol": "POLYCAB.NS", "name": "Polycab India Ltd", "sector": "Industrials"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems Ltd", "sector": "Technology"},
    {"symbol": "MAXHEALTH.NS", "name": "Max Healthcare Institute Ltd", "sector": "Healthcare"}
]

NIFTY_100 = NIFTY_50 + NIFTY_NEXT_50

# Broad Nifty 500 universe (curated actively traded companies across market caps)
NIFTY_MID_SMALL_EXT = [
    {"symbol": "AARTIIND.NS", "name": "Aarti Industries Ltd", "sector": "Chemicals"},
    {"symbol": "AAVAS.NS", "name": "Aavas Financiers Ltd", "sector": "Financial Services"},
    {"symbol": "ABFRL.NS", "name": "Aditya Birla Fashion and Retail", "sector": "Retail"},
    {"symbol": "ACC.NS", "name": "ACC Ltd", "sector": "Materials"},
    {"symbol": "ACE.NS", "name": "Action Construction Equipment", "sector": "Industrials"},
    {"symbol": "AFFLE.NS", "name": "Affle India Ltd", "sector": "Technology"},
    {"symbol": "AJANTPHARM.NS", "name": "Ajanta Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "ALKEM.NS", "name": "Alkem Laboratories Ltd", "sector": "Healthcare"},
    {"symbol": "ALKYLAMINE.NS", "name": "Alkyl Amines Chemicals Ltd", "sector": "Chemicals"},
    {"symbol": "ANGELONE.NS", "name": "Angel One Ltd", "sector": "Financial Services"},
    {"symbol": "APARINDS.NS", "name": "Apar Industries Ltd", "sector": "Industrials"},
    {"symbol": "APLAPOLLO.NS", "name": "APL Apollo Tubes Ltd", "sector": "Metals"},
    {"symbol": "ASTRAL.NS", "name": "Astral Ltd", "sector": "Industrials"},
    {"symbol": "ASTRAZEN.NS", "name": "AstraZeneca Pharma India", "sector": "Healthcare"},
    {"symbol": "ATUL.NS", "name": "Atul Ltd", "sector": "Chemicals"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "AUBANK.NS", "name": "AU Small Finance Bank", "sector": "Financial Services"},
    {"symbol": "BALKRISIND.NS", "name": "Balkrishna Industries Ltd", "sector": "Automobile"},
    {"symbol": "BALRAMCHIN.NS", "name": "Balrampur Chini Mills Ltd", "sector": "Consumer Goods"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank Ltd", "sector": "Financial Services"},
    {"symbol": "BATAINDIA.NS", "name": "Bata India Ltd", "sector": "Consumer Goods"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints India Ltd", "sector": "Consumer Goods"},
    {"symbol": "BHARATFORG.NS", "name": "Bharat Forge Ltd", "sector": "Industrials"},
    {"symbol": "BHEL.NS", "name": "Bharat Heavy Electricals Ltd", "sector": "Industrials"},
    {"symbol": "BIOCON.NS", "name": "Biocon Ltd", "sector": "Healthcare"},
    {"symbol": "BIRLACORPN.NS", "name": "Birla Corporation Ltd", "sector": "Materials"},
    {"symbol": "BLUEDART.NS", "name": "Blue Dart Express Ltd", "sector": "Logistics"},
    {"symbol": "BLUESTARCO.NS", "name": "Blue Star Ltd", "sector": "Consumer Goods"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries Ltd", "sector": "Consumer Goods"},
    {"symbol": "BSOFT.NS", "name": "Birlasoft Ltd", "sector": "Technology"},
    {"symbol": "CAMS.NS", "name": "Computer Age Management Services", "sector": "Financial Services"},
    {"symbol": "CANFINHOME.NS", "name": "Can Fin Homes Ltd", "sector": "Financial Services"},
    {"symbol": "CARBORUNIV.NS", "name": "Carborundum Universal Ltd", "sector": "Industrials"},
    {"symbol": "CASTROLIND.NS", "name": "Castrol India Ltd", "sector": "Energy"},
    {"symbol": "CDSL.NS", "name": "Central Depository Services India", "sector": "Financial Services"},
    {"symbol": "CENTURYTEX.NS", "name": "Century Textiles & Industries", "sector": "Materials"},
    {"symbol": "CESC.NS", "name": "CESC Ltd", "sector": "Utilities"},
    {"symbol": "CHAMBLFERT.NS", "name": "Chambal Fertilisers & Chem", "sector": "Chemicals"},
    {"symbol": "CLEAN.NS", "name": "Clean Science and Technology", "sector": "Chemicals"},
    {"symbol": "COCHINSHIP.NS", "name": "Cochin Shipyard Ltd", "sector": "Industrials"},
    {"symbol": "COFORGE.NS", "name": "Coforge Ltd", "sector": "Technology"},
    {"symbol": "CONCOR.NS", "name": "Container Corporation of India", "sector": "Logistics"},
    {"symbol": "COROMANDEL.NS", "name": "Coromandel International Ltd", "sector": "Chemicals"},
    {"symbol": "CROMPTON.NS", "name": "Crompton Greaves Consumer Elec", "sector": "Consumer Goods"},
    {"symbol": "CUMMINSIND.NS", "name": "Cummins India Ltd", "sector": "Industrials"},
    {"symbol": "CYIENT.NS", "name": "Cyient Ltd", "sector": "Technology"},
    {"symbol": "DEEPAKNTR.NS", "name": "Deepak Nitrite Ltd", "sector": "Chemicals"},
    {"symbol": "DELHIVERY.NS", "name": "Delhivery Ltd", "sector": "Logistics"},
    {"symbol": "DEVYANI.NS", "name": "Devyani International Ltd", "sector": "Consumer Services"},
    {"symbol": "DIXON.NS", "name": "Dixon Technologies India Ltd", "sector": "Industrials"},
    {"symbol": "LALPATHLAB.NS", "name": "Dr. Lal PathLabs Ltd", "sector": "Healthcare"},
    {"symbol": "EIDPARRY.NS", "name": "E.I.D. - Parry (India) Ltd", "sector": "Chemicals"},
    {"symbol": "EIHOTEL.NS", "name": "EIH Ltd (Oberoi Group)", "sector": "Consumer Services"},
    {"symbol": "ELGIEQUIP.NS", "name": "Elgi Equipments Ltd", "sector": "Industrials"},
    {"symbol": "EMAMILTD.NS", "name": "Emami Ltd", "sector": "Consumer Goods"},
    {"symbol": "ENDURANCE.NS", "name": "Endurance Technologies Ltd", "sector": "Automobile"},
    {"symbol": "ENGINERSIN.NS", "name": "Engineers India Ltd", "sector": "Industrials"},
    {"symbol": "EPL.NS", "name": "EPL Ltd", "sector": "Materials"},
    {"symbol": "ESCORTS.NS", "name": "Escorts Kubota Ltd", "sector": "Automobile"},
    {"symbol": "EXIDEIND.NS", "name": "Exide Industries Ltd", "sector": "Automobile"},
    {"symbol": "FACT.NS", "name": "Fertilisers & Chemicals Travancore", "sector": "Chemicals"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank Ltd", "sector": "Financial Services"},
    {"symbol": "FINCABLES.NS", "name": "Finolex Cables Ltd", "sector": "Industrials"},
    {"symbol": "FINEORG.NS", "name": "Fine Organic Industries Ltd", "sector": "Chemicals"},
    {"symbol": "FORTIS.NS", "name": "Fortis Healthcare Ltd", "sector": "Healthcare"},
    {"symbol": "GLAXO.NS", "name": "GlaxoSmithKline Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "GLENMARK.NS", "name": "Glenmark Pharmaceuticals Ltd", "sector": "Healthcare"},
    {"symbol": "GMRINFRA.NS", "name": "GMR Airports Infrastructure Ltd", "sector": "Infrastructure"},
    {"symbol": "GNFC.NS", "name": "Gujarat Narmada Valley Fert", "sector": "Chemicals"},
    {"symbol": "GODREJIND.NS", "name": "Godrej Industries Ltd", "sector": "Diversified"},
    {"symbol": "GODREJPROP.NS", "name": "Godrej Properties Ltd", "sector": "Real Estate"},
    {"symbol": "GRANULES.NS", "name": "Granules India Ltd", "sector": "Healthcare"},
    {"symbol": "GRAPHITE.NS", "name": "Graphite India Ltd", "sector": "Industrials"},
    {"symbol": "GSFC.NS", "name": "Gujarat State Fertilizers & Chem", "sector": "Chemicals"},
    {"symbol": "GSPL.NS", "name": "Gujarat State Petronet Ltd", "sector": "Utilities"},
    {"symbol": "GUJGASLTD.NS", "name": "Gujarat Gas Ltd", "sector": "Utilities"},
    {"symbol": "HAPPSTMNDS.NS", "name": "Happiest Minds Technologies", "sector": "Technology"},
    {"symbol": "HEG.NS", "name": "HEG Ltd", "sector": "Industrials"},
    {"symbol": "HFCL.NS", "name": "HFCL Ltd", "sector": "Telecommunications"},
    {"symbol": "HINDCOPPER.NS", "name": "Hindustan Copper Ltd", "sector": "Metals"},
    {"symbol": "HINDPETRO.NS", "name": "Hindustan Petroleum Corp Ltd", "sector": "Energy"},
    {"symbol": "HINDZINC.NS", "name": "Hindustan Zinc Ltd", "sector": "Metals"},
    {"symbol": "HONAUT.NS", "name": "Honeywell Automation India", "sector": "Technology"},
    {"symbol": "HUDCO.NS", "name": "Housing & Urban Development Corp", "sector": "Financial Services"},
    {"symbol": "IDBI.NS", "name": "IDBI Bank Ltd", "sector": "Financial Services"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank Ltd", "sector": "Financial Services"},
    {"symbol": "IEX.NS", "name": "Indian Energy Exchange Ltd", "sector": "Financial Services"},
    {"symbol": "IGL.NS", "name": "Indraprastha Gas Ltd", "sector": "Utilities"},
    {"symbol": "INDHOTEL.NS", "name": "Indian Hotels Co Ltd", "sector": "Consumer Services"},
    {"symbol": "INDIACEM.NS", "name": "India Cements Ltd", "sector": "Materials"},
    {"symbol": "INDIAMART.NS", "name": "IndiaMART InterMESH Ltd", "sector": "Technology"},
    {"symbol": "IPCALAB.NS", "name": "IPCA Laboratories Ltd", "sector": "Healthcare"},
    {"symbol": "JBCHEPHARM.NS", "name": "JB Chemicals & Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "JKCEMENT.NS", "name": "JK Cement Ltd", "sector": "Materials"},
    {"symbol": "JKPAPER.NS", "name": "JK Paper Ltd", "sector": "Materials"},
    {"symbol": "JSL.NS", "name": "Jindal Stainless Ltd", "sector": "Metals"},
    {"symbol": "JSWENERGY.NS", "name": "JSW Energy Ltd", "sector": "Utilities"},
    {"symbol": "JSWINFRA.NS", "name": "JSW Infrastructure Ltd", "sector": "Infrastructure"},
    {"symbol": "JUBLFOOD.NS", "name": "Jubilant FoodWorks Ltd", "sector": "Consumer Services"},
    {"symbol": "JUBLINGREA.NS", "name": "Jubilant Ingrevia Ltd", "sector": "Chemicals"},
    {"symbol": "JUBLPHARMA.NS", "name": "Jubilant Pharmova Ltd", "sector": "Healthcare"},
    {"symbol": "KALYANKJIL.NS", "name": "Kalyan Jewellers India Ltd", "sector": "Consumer Goods"},
    {"symbol": "KANSAINER.NS", "name": "Kansai Nerolac Paints Ltd", "sector": "Consumer Goods"},
    {"symbol": "KARURVYSYA.NS", "name": "Karur Vysya Bank Ltd", "sector": "Financial Services"},
    {"symbol": "KEC.NS", "name": "KEC International Ltd", "sector": "Industrials"},
    {"symbol": "KEI.NS", "name": "KEI Industries Ltd", "sector": "Industrials"},
    {"symbol": "KFINTECH.NS", "name": "KFin Technologies Ltd", "sector": "Financial Services"},
    {"symbol": "KNRCON.NS", "name": "KNR Constructions Ltd", "sector": "Construction"},
    {"symbol": "KPITTECH.NS", "name": "KPIT Technologies Ltd", "sector": "Technology"},
    {"symbol": "KRBL.NS", "name": "KRBL Ltd", "sector": "Consumer Goods"},
    {"symbol": "L&TFH.NS", "name": "L&T Finance Ltd", "sector": "Financial Services"},
    {"symbol": "LAURUSLABS.NS", "name": "Laurus Labs Ltd", "sector": "Healthcare"},
    {"symbol": "LICHSGFIN.NS", "name": "LIC Housing Finance Ltd", "sector": "Financial Services"},
    {"symbol": "LINDEINDIA.NS", "name": "Linde India Ltd", "sector": "Chemicals"},
    {"symbol": "LUPIN.NS", "name": "Lupin Ltd", "sector": "Healthcare"},
    {"symbol": "M&MFIN.NS", "name": "Mahindra & Mahindra Financial", "sector": "Financial Services"},
    {"symbol": "MAHABANK.NS", "name": "Bank of Maharashtra", "sector": "Financial Services"},
    {"symbol": "MANAPPURAM.NS", "name": "Manappuram Finance Ltd", "sector": "Financial Services"},
    {"symbol": "MANKIND.NS", "name": "Mankind Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "MAPMYINDIA.NS", "name": "C.E. Info Systems (MapMyIndia)", "sector": "Technology"},
    {"symbol": "MARSHALL.NS", "name": "Marshall Machines Ltd", "sector": "Industrials"},
    {"symbol": "MASTEK.NS", "name": "Mastek Ltd", "sector": "Technology"},
    {"symbol": "MAXESTATES.NS", "name": "Max Estates Ltd", "sector": "Real Estate"},
    {"symbol": "MAZDOCK.NS", "name": "Mazagon Dock Shipbuilders", "sector": "Industrials"},
    {"symbol": "MEDANTA.NS", "name": "Global Health Ltd (Medanta)", "sector": "Healthcare"},
    {"symbol": "METROPOLIS.NS", "name": "Metropolis Healthcare Ltd", "sector": "Healthcare"},
    {"symbol": "MFSL.NS", "name": "Max Financial Services Ltd", "sector": "Financial Services"},
    {"symbol": "MGL.NS", "name": "Mahanagar Gas Ltd", "sector": "Utilities"},
    {"symbol": "MINDACORP.NS", "name": "Minda Corporation Ltd", "sector": "Automobile"},
    {"symbol": "MOTILALOFS.NS", "name": "Motilal Oswal Financial Serv", "sector": "Financial Services"},
    {"symbol": "MPHASIS.NS", "name": "Mphasis Ltd", "sector": "Technology"},
    {"symbol": "MRF.NS", "name": "MRF Ltd", "sector": "Automobile"},
    {"symbol": "MRPL.NS", "name": "Mangalore Refinery & Petrochem", "sector": "Energy"},
    {"symbol": "NAM-INDIA.NS", "name": "Nippon Life India Asset Mgmt", "sector": "Financial Services"},
    {"symbol": "NATCOPHARM.NS", "name": "Natco Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "NATIONALUM.NS", "name": "National Aluminium Co Ltd", "sector": "Metals"},
    {"symbol": "NAVINFLUOR.NS", "name": "Navin Fluorine International", "sector": "Chemicals"},
    {"symbol": "NBCC.NS", "name": "NBCC (India) Ltd", "sector": "Construction"},
    {"symbol": "NCC.NS", "name": "NCC Ltd", "sector": "Construction"},
    {"symbol": "NESCO.NS", "name": "Nesco Ltd", "sector": "Industrials"},
    {"symbol": "NETWORK18.NS", "name": "Network18 Media & Investments", "sector": "Media"},
    {"symbol": "NLCINDIA.NS", "name": "NLC India Ltd", "sector": "Energy"},
    {"symbol": "NMDC.NS", "name": "NMDC Ltd", "sector": "Metals & Mining"},
    {"symbol": "NOCIL.NS", "name": "NOCIL Ltd", "sector": "Chemicals"},
    {"symbol": "NUVAMA.NS", "name": "Nuvama Wealth Management", "sector": "Financial Services"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoi Realty Ltd", "sector": "Real Estate"},
    {"symbol": "OFSS.NS", "name": "Oracle Financial Services Software", "sector": "Technology"},
    {"symbol": "OIL.NS", "name": "Oil India Ltd", "sector": "Energy"},
    {"symbol": "OLECTRA.NS", "name": "Olectra Greentech Ltd", "sector": "Automobile"},
    {"symbol": "PAGEIND.NS", "name": "Page Industries Ltd", "sector": "Consumer Goods"},
    {"symbol": "PATANJALI.NS", "name": "Patanjali Foods Ltd", "sector": "Consumer Goods"},
    {"symbol": "PAYTM.NS", "name": "One97 Communications (Paytm)", "sector": "Technology"},
    {"symbol": "PEL.NS", "name": "Piramal Enterprises Ltd", "sector": "Financial Services"},
    {"symbol": "PETRONET.NS", "name": "Petronet LNG Ltd", "sector": "Energy"},
    {"symbol": "PHOENIXLTD.NS", "name": "The Phoenix Mills Ltd", "sector": "Real Estate"},
    {"symbol": "PIIND.NS", "name": "PI Industries Ltd", "sector": "Chemicals"},
    {"symbol": "PNBHOUSING.NS", "name": "PNB Housing Finance Ltd", "sector": "Financial Services"},
    {"symbol": "POLICYBZR.NS", "name": "PB Fintech (PolicyBazaar)", "sector": "Financial Services"},
    {"symbol": "POONAWALLA.NS", "name": "Poonawalla Fincorp Ltd", "sector": "Financial Services"},
    {"symbol": "PPLPHARMA.NS", "name": "Piramal Pharma Ltd", "sector": "Healthcare"},
    {"symbol": "PRESTIGE.NS", "name": "Prestige Estates Projects", "sector": "Real Estate"},
    {"symbol": "PRINCEPIPE.NS", "name": "Prince Pipes and Fittings Ltd", "sector": "Industrials"},
    {"symbol": "PRSMJOHNSN.NS", "name": "Prism Johnson Ltd", "sector": "Materials"},
    {"symbol": "PVRINOX.NS", "name": "PVR INOX Ltd", "sector": "Consumer Services"},
    {"symbol": "RADICO.NS", "name": "Radico Khaitan Ltd", "sector": "Consumer Goods"},
    {"symbol": "RVNL.NS", "name": "Rail Vikas Nigam Ltd", "sector": "Construction"},
    {"symbol": "RAILTEL.NS", "name": "RailTel Corp of India Ltd", "sector": "Telecommunications"},
    {"symbol": "RAINBOW.NS", "name": "Rainbow Children's Medicare", "sector": "Healthcare"},
    {"symbol": "RAJESHEXPO.NS", "name": "Rajesh Exports Ltd", "sector": "Consumer Goods"},
    {"symbol": "RALLIS.NS", "name": "Rallis India Ltd", "sector": "Chemicals"},
    {"symbol": "RAMCOCEM.NS", "name": "The Ramco Cements Ltd", "sector": "Materials"},
    {"symbol": "RBLBANK.NS", "name": "RBL Bank Ltd", "sector": "Financial Services"},
    {"symbol": "RCF.NS", "name": "Rashtriya Chemicals & Fert", "sector": "Chemicals"},
    {"symbol": "REDINGTON.NS", "name": "Redington Ltd", "sector": "Services"},
    {"symbol": "RELAXO.NS", "name": "Relaxo Footwears Ltd", "sector": "Consumer Goods"},
    {"symbol": "RITES.NS", "name": "RITES Ltd", "sector": "Construction"},
    {"symbol": "ROLEXRINGS.NS", "name": "Rolex Rings Ltd", "sector": "Automobile"},
    {"symbol": "ROUTE.NS", "name": "Route Mobile Ltd", "sector": "Technology"},
    {"symbol": "RRKABEL.NS", "name": "R R Kabel Ltd", "sector": "Industrials"},
    {"symbol": "SAFARI.NS", "name": "Safari Industries (India) Ltd", "sector": "Consumer Goods"},
    {"symbol": "SAIL.NS", "name": "Steel Authority of India Ltd", "sector": "Metals"},
    {"symbol": "SANOFI.NS", "name": "Sanofi India Ltd", "sector": "Healthcare"},
    {"symbol": "SAPPHIRE.NS", "name": "Sapphire Foods India Ltd", "sector": "Consumer Services"},
    {"symbol": "SCHAEFFLER.NS", "name": "Schaeffler India Ltd", "sector": "Automobile"},
    {"symbol": "SCHNEIDER.NS", "name": "Schneider Electric Infrastructure", "sector": "Industrials"},
    {"symbol": "SHOPERSTOP.NS", "name": "Shoppers Stop Ltd", "sector": "Retail"},
    {"symbol": "SHREECEM.NS", "name": "Shree Cement Ltd", "sector": "Materials"},
    {"symbol": "SHRIRAMPPS.NS", "name": "Shriram Properties Ltd", "sector": "Real Estate"},
    {"symbol": "SJVN.NS", "name": "SJVN Ltd", "sector": "Utilities"},
    {"symbol": "SKFINDIA.NS", "name": "SKF India Ltd", "sector": "Industrials"},
    {"symbol": "SOBHA.NS", "name": "Sobha Ltd", "sector": "Real Estate"},
    {"symbol": "SOLARINDS.NS", "name": "Solar Industries India Ltd", "sector": "Chemicals"},
    {"symbol": "SONACOMS.NS", "name": "Sona BLW Precision Forgings", "sector": "Automobile"},
    {"symbol": "STARHEALTH.NS", "name": "Star Health & Allied Insurance", "sector": "Financial Services"},
    {"symbol": "SUMICHEM.NS", "name": "Sumitomo Chemical India Ltd", "sector": "Chemicals"},
    {"symbol": "SUNDARMFIN.NS", "name": "Sundaram Finance Ltd", "sector": "Financial Services"},
    {"symbol": "SUNDRMFAST.NS", "name": "Sundram Fasteners Ltd", "sector": "Automobile"},
    {"symbol": "SUNTV.NS", "name": "Sun TV Network Ltd", "sector": "Media"},
    {"symbol": "SUPREMEIND.NS", "name": "Supreme Industries Ltd", "sector": "Industrials"},
    {"symbol": "SUZLON.NS", "name": "Suzlon Energy Ltd", "sector": "Utilities"},
    {"symbol": "SWANENERGY.NS", "name": "Swan Energy Ltd", "sector": "Energy"},
    {"symbol": "SYMPHONY.NS", "name": "Symphony Ltd", "sector": "Consumer Goods"},
    {"symbol": "SYNGENE.NS", "name": "Syngene International Ltd", "sector": "Healthcare"},
    {"symbol": "TATACHEM.NS", "name": "Tata Chemicals Ltd", "sector": "Chemicals"},
    {"symbol": "TATACOMM.NS", "name": "Tata Communications Ltd", "sector": "Telecommunications"},
    {"symbol": "TATAELXSI.NS", "name": "Tata Elxsi Ltd", "sector": "Technology"},
    {"symbol": "TATAINVEST.NS", "name": "Tata Investment Corp Ltd", "sector": "Financial Services"},
    {"symbol": "TATAMTRDVR.NS", "name": "Tata Motors Ltd DVR", "sector": "Automobile"},
    {"symbol": "TATATECH.NS", "name": "Tata Technologies Ltd", "sector": "Technology"},
    {"symbol": "TEJASNET.NS", "name": "Tejas Networks Ltd", "sector": "Telecommunications"},
    {"symbol": "THERMAX.NS", "name": "Thermax Ltd", "sector": "Industrials"},
    {"symbol": "TIMKEN.NS", "name": "Timken India Ltd", "sector": "Industrials"},
    {"symbol": "TITAGARH.NS", "name": "Titagarh Rail Systems Ltd", "sector": "Industrials"},
    {"symbol": "TRIDENT.NS", "name": "Trident Ltd", "sector": "Textiles"},
    {"symbol": "TRITURBINE.NS", "name": "Triveni Turbine Ltd", "sector": "Industrials"},
    {"symbol": "TRIVENI.NS", "name": "Triveni Engineering & Ind", "sector": "Consumer Goods"},
    {"symbol": "TTML.NS", "name": "Tata Teleservices (Maharashtra)", "sector": "Telecommunications"},
    {"symbol": "UCOBANK.NS", "name": "UCO Bank", "sector": "Financial Services"},
    {"symbol": "UPL.NS", "name": "UPL Ltd", "sector": "Chemicals"},
    {"symbol": "UTIAMC.NS", "name": "UTI Asset Management Co Ltd", "sector": "Financial Services"},
    {"symbol": "VAIBHAVGBL.NS", "name": "Vaibhav Global Ltd", "sector": "Retail"},
    {"symbol": "VGUARD.NS", "name": "V-Guard Industries Ltd", "sector": "Consumer Goods"},
    {"symbol": "VIJAYA.NS", "name": "Vijaya Diagnostic Centre Ltd", "sector": "Healthcare"},
    {"symbol": "VINATIORGA.NS", "name": "Vinati Organics Ltd", "sector": "Chemicals"},
    {"symbol": "VIPIND.NS", "name": "VIP Industries Ltd", "sector": "Consumer Goods"},
    {"symbol": "VOLTAS.NS", "name": "Voltas Ltd", "sector": "Consumer Goods"},
    {"symbol": "WELCORP.NS", "name": "Welspun Corp Ltd", "sector": "Metals"},
    {"symbol": "WELSPUNLIV.NS", "name": "Welspun Living Ltd", "sector": "Textiles"},
    {"symbol": "WESTLIFE.NS", "name": "Westlife Foodworld Ltd", "sector": "Consumer Services"},
    {"symbol": "WHIRLPOOL.NS", "name": "Whirlpool of India Ltd", "sector": "Consumer Goods"},
    {"symbol": "YESBANK.NS", "name": "Yes Bank Ltd", "sector": "Financial Services"},
    {"symbol": "ZEEL.NS", "name": "Zee Entertainment Enterprises", "sector": "Media"},
    {"symbol": "ZENSARTECH.NS", "name": "Zensar Technologies Ltd", "sector": "Technology"}
]

NIFTY_500 = NIFTY_100 + NIFTY_MID_SMALL_EXT

BANK_NIFTY = [
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Ltd", "sector": "Banking"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Ltd", "sector": "Banking"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "sector": "Banking"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Ltd", "sector": "Banking"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Ltd", "sector": "Banking"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd", "sector": "Banking"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda", "sector": "Banking"},
    {"symbol": "PNB.NS", "name": "Punjab National Bank", "sector": "Banking"},
    {"symbol": "AUBANK.NS", "name": "AU Small Finance Bank", "sector": "Banking"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank Ltd", "sector": "Banking"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank Ltd", "sector": "Banking"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank Ltd", "sector": "Banking"},
    {"symbol": "CANBK.NS", "name": "Canara Bank", "sector": "Banking"},
    {"symbol": "UNIONBANK.NS", "name": "Union Bank of India", "sector": "Banking"},
    {"symbol": "RBLBANK.NS", "name": "RBL Bank Ltd", "sector": "Banking"}
]

NSE_UNIVERSES = {
    "nifty_50": {"name": "Nifty 50 (Bluechips)", "tickers": NIFTY_50},
    "bank_nifty": {"name": "Bank Nifty (Banking Sector)", "tickers": BANK_NIFTY},
    "nifty_100": {"name": "Nifty 100 (Large Cap)", "tickers": NIFTY_100},
    "nifty_500": {"name": "Nifty 500 (Broad Market)", "tickers": NIFTY_500},
}

