"""
US Market Ticker Universes
Includes S&P 500 and top actively traded NYSE / NASDAQ equities.
"""

SP_500_TOP = [
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "sector": "Consumer Cyclical", "exchange": "NASDAQ"},
    {"symbol": "GOOGL", "name": "Alphabet Inc. (Google)", "sector": "Communication Services", "exchange": "NASDAQ"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "sector": "Communication Services", "exchange": "NASDAQ"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "sector": "Consumer Cyclical", "exchange": "NASDAQ"},
    {"symbol": "BRK-B", "name": "Berkshire Hathaway Inc.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "LLY", "name": "Eli Lilly and Company", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "V", "name": "Visa Inc.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "UNH", "name": "UnitedHealth Group Inc.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "XOM", "name": "Exxon Mobil Corporation", "sector": "Energy", "exchange": "NYSE"},
    {"symbol": "MA", "name": "Mastercard Incorporated", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "PG", "name": "Procter & Gamble Co.", "sector": "Consumer Defensive", "exchange": "NYSE"},
    {"symbol": "COST", "name": "Costco Wholesale Corp.", "sector": "Consumer Defensive", "exchange": "NASDAQ"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "HD", "name": "The Home Depot Inc.", "sector": "Consumer Cyclical", "exchange": "NYSE"},
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Defensive", "exchange": "NYSE"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "sector": "Communication Services", "exchange": "NASDAQ"},
    {"symbol": "BAC", "name": "Bank of America Corp.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "CVX", "name": "Chevron Corporation", "sector": "Energy", "exchange": "NYSE"},
    {"symbol": "KO", "name": "The Coca-Cola Company", "sector": "Consumer Defensive", "exchange": "NYSE"},
    {"symbol": "MRK", "name": "Merck & Co. Inc.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "AMD", "name": "Advanced Micro Devices Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "sector": "Consumer Defensive", "exchange": "NASDAQ"},
    {"symbol": "LIN", "name": "Linde plc", "sector": "Basic Materials", "exchange": "NASDAQ"},
    {"symbol": "ACN", "name": "Accenture plc", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "sector": "Consumer Cyclical", "exchange": "NYSE"},
    {"symbol": "CSCO", "name": "Cisco Systems Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "GE", "name": "General Electric Company", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "WFC", "name": "Wells Fargo & Company", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "IBM", "name": "International Business Machines", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "QCOM", "name": "Qualcomm Incorporated", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "TXN", "name": "Texas Instruments Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "VZ", "name": "Verizon Communications Inc.", "sector": "Communication Services", "exchange": "NYSE"},
    {"symbol": "DIS", "name": "The Walt Disney Company", "sector": "Communication Services", "exchange": "NYSE"},
    {"symbol": "PM", "name": "Philip Morris International", "sector": "Consumer Defensive", "exchange": "NYSE"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Healthcare", "exchange": "NASDAQ"},
    {"symbol": "ISRG", "name": "Intuitive Surgical Inc.", "sector": "Healthcare", "exchange": "NASDAQ"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "UBER", "name": "Uber Technologies Inc.", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "GS", "name": "The Goldman Sachs Group", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "BLK", "name": "BlackRock Inc.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "INTC", "name": "Intel Corporation", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "BA", "name": "The Boeing Company", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "HON", "name": "Honeywell International Inc.", "sector": "Industrials", "exchange": "NASDAQ"},
    {"symbol": "RTX", "name": "RTX Corporation", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "LOW", "name": "Lowe's Companies Inc.", "sector": "Consumer Cyclical", "exchange": "NYSE"},
    {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy", "exchange": "NYSE"},
    {"symbol": "SPGI", "name": "S&P Global Inc.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "UNP", "name": "Union Pacific Corporation", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "SYK", "name": "Stryker Corporation", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "NKE", "name": "NIKE Inc.", "sector": "Consumer Cyclical", "exchange": "NYSE"},
    {"symbol": "PLTR", "name": "Palantir Technologies Inc.", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "PANW", "name": "Palo Alto Networks Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "DE", "name": "Deere & Company", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc.", "sector": "Consumer Cyclical", "exchange": "NASDAQ"},
    {"symbol": "BMY", "name": "Bristol-Myers Squibb Company", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "MDT", "name": "Medtronic plc", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "ADI", "name": "Analog Devices Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Inc.", "sector": "Healthcare", "exchange": "NASDAQ"},
    {"symbol": "CI", "name": "The Cigna Group", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "TJX", "name": "The TJX Companies Inc.", "sector": "Consumer Cyclical", "exchange": "NYSE"},
    {"symbol": "CB", "name": "Chubb Limited", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "C", "name": "Citigroup Inc.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "CVS", "name": "CVS Health Corporation", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "SO", "name": "The Southern Company", "sector": "Utilities", "exchange": "NYSE"},
    {"symbol": "DUK", "name": "Duke Energy Corporation", "sector": "Utilities", "exchange": "NYSE"},
    {"symbol": "PGR", "name": "The Progressive Corporation", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "BSX", "name": "Boston Scientific Corp.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "SCHW", "name": "The Charles Schwab Corp.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "ZTS", "name": "Zoetis Inc.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "MO", "name": "Altria Group Inc.", "sector": "Consumer Defensive", "exchange": "NYSE"},
    {"symbol": "MMC", "name": "Marsh & McLennan Companies", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "ETN", "name": "Eaton Corporation plc", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "FI", "name": "Fiserv Inc.", "sector": "Technology", "exchange": "NYSE"},
    {"symbol": "SHW", "name": "The Sherwin-Williams Company", "sector": "Basic Materials", "exchange": "NYSE"},
    {"symbol": "ITW", "name": "Illinois Tool Works Inc.", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "BDX", "name": "Becton Dickinson and Co.", "sector": "Healthcare", "exchange": "NYSE"},
    {"symbol": "EOG", "name": "EOG Resources Inc.", "sector": "Energy", "exchange": "NYSE"},
    {"symbol": "SLB", "name": "Schlumberger Limited", "sector": "Energy", "exchange": "NYSE"},
    {"symbol": "CL", "name": "Colgate-Palmolive Company", "sector": "Consumer Defensive", "exchange": "NYSE"},
    {"symbol": "MU", "name": "Micron Technology Inc.", "sector": "Technology", "exchange": "NASDAQ"},
    {"symbol": "WM", "name": "Waste Management Inc.", "sector": "Industrials", "exchange": "NYSE"},
    {"symbol": "USB", "name": "U.S. Bancorp", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "PNC", "name": "The PNC Financial Services Group", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "ICE", "name": "Intercontinental Exchange Inc.", "sector": "Financial Services", "exchange": "NYSE"},
    {"symbol": "CME", "name": "CME Group Inc.", "sector": "Financial Services", "exchange": "NASDAQ"}
]

NYSE_TOP = [
    s for s in SP_500_TOP if s.get("exchange") == "NYSE"
]

US_UNIVERSES = {
    "sp_500_top": {"name": "S&P 100 / Large Cap Leaders", "tickers": SP_500_TOP},
    "nyse_top": {"name": "NYSE Blue Chips", "tickers": NYSE_TOP},
}
